export const CONTACT_STATUS = {
  CONTACTED: 'CONTACTED',
  NOT_CONTACTED: 'NOT_CONTACTED',
  TRIAL_REGISTERED_PARTIAL: 'TRIAL_REGISTERED_PARTIAL',
  TRIAL_REGISTERED_ALL: 'TRIAL_REGISTERED_ALL',
  TRIAL_ATTENDED_PARTIAL: 'TRIAL_ATTENDED_PARTIAL',
  TRIAL_ATTENDED_ALL: 'TRIAL_ATTENDED_ALL',
};

