export const TEACHING_SCHEDULE_STATUS = {
  UPCOMING: 'UPCOMING',
  NOT_CHECKED_IN: 'NOT_CHECKED_IN',
  CHECKED_IN: 'CHECKED_IN',
  CHECKED_IN_LATE: 'CHECKED_IN_LATE',
  CHECKED_OUT: 'CHECKED_OUT',
  CHECKED_OUT_EARLY: 'CHECKED_OUT_EARLY',
} as const;

export type TeachingScheduleStatus =
  (typeof TEACHING_SCHEDULE_STATUS)[keyof typeof TEACHING_SCHEDULE_STATUS];


